
from numpy import (
    abs,
    append,
    arange,
    arccos,
    array,
    arcsin,
    arctan,
    column_stack,
    cos,
    dot,
    empty,
    eye,
    insert,
    interp,
    linspace,
    ndarray,
    ones,
    pi,
    repeat,
    sin,
    vstack,
    zeros,
)
from numpy.random import (
    normal,
    random,
    uniform,
)
abs(12)
import pyqtgraph as pg

# ==== QT IMPORTS ====
from PySide6.QtCore import (
    QDataStream,
    QDir,
    QLineF,
    QRectF,
    QRunnable,
    Signal,
    Slot,
    QSize,
    Qt,
    QThreadPool,
    QTimer,
)
from PySide6.QtGui import (
    QAction,
    QColor,
    QFont,
    QIcon,
    QImage,
    QKeySequence,
    QPixmap,
    QPalette,
    QPainter,
    QTextFormat,
)
from PySide6.QtNetwork import (
    QAbstractSocket,
    QHostAddress,
    QTcpSocket,
)
from PySide6.QtWidgets import (
    QApplication,
    QComboBox,
    QDialog,
    QFileDialog,
    QGraphicsLineItem,
    QGraphicsRectItem,
    QGraphicsView,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLCDNumber,
    QLineEdit,
    QMainWindow,
    QMenuBar,
    QMessageBox,
    QPushButton,
    QSizePolicy,
    QSpinBox,
    QSplitter,
    QStackedWidget,
    QStatusBar,
    QTextEdit,
    QToolBar,
    QToolButton,
    QVBoxLayout,
    QWidget,
)


# # ==== QT IMPORTS ====
# from PyQt5.QtCore import (
#     QDataStream,
#     QDir,
#     QLineF,
#     QRectF,
#     QRunnable,
#     QSize,
#     Qt,
#     QThreadPool,
#     QTimer,
# )
# from PyQt5.QtGui import (
#     QColor,
#     QFont,
#     QIcon,
#     QImage,
#     QKeySequence,
#     QPixmap,
#     QPalette,
#     QPainter,
#     QTextFormat,
# )
# from PyQt5.QtNetwork import (
#     QAbstractSocket,
#     QHostAddress,
#     QTcpSocket,
# )
# from PyQt5.QtWidgets import (
#     QAction,
#     QActionGroup,
#     QApplication,
#     QComboBox,
#     QDialog,
#     QFileDialog,
#     QGraphicsLineItem,
#     QGraphicsRectItem,
#     QGraphicsView,
#     QGridLayout,
#     QGroupBox,
#     QHBoxLayout,
#     QLabel,
#     QLCDNumber,
#     QLineEdit,
#     QMainWindow,
#     QMenuBar,
#     QMessageBox,
#     QPushButton,
#     QSizePolicy,
#     QSpinBox,
#     QSplitter,
#     QStackedWidget,
#     QStatusBar,
#     QTextEdit,
#     QToolBar,
#     QToolButton,
#     QVBoxLayout,
#     QWidget,
# )
#
#
